CLASS zz1_cl_bomcau DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF ZZ1_I_BOMCAU.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZZ1_CL_BOMCAU IMPLEMENTATION.
ENDCLASS.
